### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhuya1996** [wuhuikai/FaceSwap#38]
File "main.py", line 25, in <module>
    src_points, src_shape, src_face = select_face(src_img)
  File "D:\2022waiba\ww\FaceSwap-master\face_detection.py", line 37, in select_face
    bbox = faces[idx]
TypeError: Invalid index type

**Comment by Themisfit7** [comment]
hello
please pardon i'm new here, and i was hoping to get my faceswap issues fixed with right assistance, the software redirected me here

"C:\WINDOWS\system32>"C:\Users\Lenovo\Miniconda3\scripts\activate.bat"   && conda activate "faceswap"   && python "C:\Users\faceswap/faceswap.py" gui
Setting Faceswap backend to CPU
09/22/2022 05:38:51 INFO     Log level set to: INFO
09/22/2022 05:39:02 ERROR    A DLL library file failed to load. Make sure that you have Microsoft Visual C++ Redistributable (2015, 2017, 2019) installed for your machine from: https://support.microsoft.com/en-gb/help/2977003. Original error: Traceback (most recent call last):
  File "C:\Users\Lenovo\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 60, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed."

**Comment by wuhuikai** [comment]
> hello please pardon i'm new here, and i was hoping to get my faceswap issues fixed with right assistance, the software redirected me here
> 
> "C:\WINDOWS\system32>"C:\Users\Lenovo\Miniconda3\scripts\activate.bat" && conda activate "faceswap" && python "C:\Users\faceswap/faceswap.py" gui Setting Faceswap backend to CPU 09/22/2022 05:38:51 INFO Log level set to: INFO 09/22/2022 05:39:02 ERROR A DLL library file failed to load. Make sure that you have Microsoft Visual C++ Redistributable (2015, 2017, 2019) installed for your machine from: https://support.microsoft.com/en-gb/help/2977003. Original error: Traceback (most recent call last): File "C:\Users\Lenovo\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 60, in from tensorflow.python._pywrap_tensorflow_internal import * ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed."

TensorFlow is not required by this repo.
