### ISSUE TITLE
swap video error

### ISSUE THREAD

**Issue by xiaosefengyun** [wuhuikai/FaceSwap#39]
![image](https://user-images.githubusercontent.com/12832248/178278557-05cc308a-f1e1-4da0-a77c-70ec0e042a38.png)

**Comment by wuhuikai** [comment]
Perhaps wrong dlib version or python version.

**Comment by wearenocomputer** [comment]
I have the same error. It is not the dlib version because the swapping works on images.
I think it has something to do with the first line of the error:

CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

![image](https://user-images.githubusercontent.com/3810185/188973631-6e00876e-9b6a-451d-a6bc-85b0730dae36.png)

**Comment by wearenocomputer** [comment]
It works for me by changing line 17 in the file face_swap.py

Change it to 

self.video = cv2.VideoCapture(0)

0 can be any number of camera attached to your computer. In my case it is 2 to get the usb webcam of my laptop.

![image](https://user-images.githubusercontent.com/3810185/188974973-c5933859-5135-42e1-8886-d064a2a4e76b.png)
